auth_param basic children 5 startup=2 idle=1
auth_param basic casesensitive off
# 设置密码文件缓存时间，默认60秒
auth_param basic credentialsttl 60 seconds
auth_param basic log credential on
#################################################################################
# **重点**，这里/app/docker/squid/passwd要挂载到宿主机，暴露给squid-manager管理
#################################################################################
auth_param basic program /usr/lib/squid/basic_ncsa_auth /app/docker/squid/passwd
acl auth_user proxy_auth REQUIRED
http_access allow auth_user

# 禁止所有日志
access_log none
cache_log /dev/null
logfile_rotate 0
cache_store_log none
# 完全隐藏版本信息
httpd_suppress_version_string on
via off
forwarded_for delete
# 移除所有标识性头部
reply_header_access Server deny all
reply_header_access X-Cache deny all
reply_header_access X-Squid-Error deny all
reply_header_access Via deny all
reply_header_access X-Forwarded-For deny all

#以下是高匿的设置
request_header_access Via deny all
request_header_access X-Forwarded-For deny all

http_port 3128